In [4]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline
import matplotlib
matplotlib.rcParams['figure.figsize'] = (20,10)

In [7]:
df = pd.read_csv('cardekho.csv', index_col=0)
df.head()

car_name    brand     model  vehicle_age  km_driven seller_type  \
0    Maruti Alto   Maruti      Alto            9     120000  Individual   
1  Hyundai Grand  Hyundai     Grand            5      20000  Individual   
2    Hyundai i20  Hyundai       i20           11      60000  Individual   
3    Maruti Alto   Maruti      Alto            9      37000  Individual   
4  Ford Ecosport     Ford  Ecosport            6      30000      Dealer   

  fuel_type transmission_type  mileage  engine  max_power  seats  \
0    Petrol            Manual    19.70     796      46.30      5   
1    Petrol            Manual    18.90    1197      82.00      5   
2    Petrol            Manual    17.00    1197      80.00      5   
3    Petrol            Manual    20.92     998      67.10      5   
4    Diesel            Manual    22.77    1498      98.59      5   

   selling_price  
0         120000  
1         550000  
2         215000  
3         226000  
4         570000

In [8]:
df.shape

(15411, 13)

In [9]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [11]:
df.selling_price.unique

<bound method Series.unique of 0         120000
1         550000
2         215000
3         226000
4         570000
          ...   
19537     250000
19540     925000
19541     425000
19542    1225000
19543    1200000
Name: selling_price, Length: 15411, dtype: int64>

In [12]:
df.seats.unique()

array([5, 8, 7, 6, 4, 2, 9, 0])

In [13]:
df[df.seats==0]

car_name   brand  model  vehicle_age  km_driven seller_type  \
4098     Honda City   Honda   City           18      40000  Individual   
15992  Nissan Kicks  Nissan  Kicks            2      10000  Individual   

      fuel_type transmission_type  mileage  engine  max_power  seats  \
4098     Petrol            Manual    13.00    1493     100.00      0   
15992    Diesel            Manual    19.39    1461     108.49      0   

       selling_price  
4098          115000  
15992        1154000

In [14]:
df1 = df.copy()

In [18]:
df1 = df[df.seats!=0]

In [19]:
df1.shape

(15409, 13)

In [20]:
df1.head()

car_name    brand     model  vehicle_age  km_driven seller_type  \
0    Maruti Alto   Maruti      Alto            9     120000  Individual   
1  Hyundai Grand  Hyundai     Grand            5      20000  Individual   
2    Hyundai i20  Hyundai       i20           11      60000  Individual   
3    Maruti Alto   Maruti      Alto            9      37000  Individual   
4  Ford Ecosport     Ford  Ecosport            6      30000      Dealer   

  fuel_type transmission_type  mileage  engine  max_power  seats  \
0    Petrol            Manual    19.70     796      46.30      5   
1    Petrol            Manual    18.90    1197      82.00      5   
2    Petrol            Manual    17.00    1197      80.00      5   
3    Petrol            Manual    20.92     998      67.10      5   
4    Diesel            Manual    22.77    1498      98.59      5   

   selling_price  
0         120000  
1         550000  
2         215000  
3         226000  
4         570000

In [22]:
df1.max_power.unique

<bound method Series.unique of 0         46.30
1         82.00
2         80.00
3         67.10
4         98.59
          ...  
19537     68.05
19540     91.10
19541    103.52
19542    140.00
19543    117.60
Name: max_power, Length: 15409, dtype: float64>

In [24]:
def is_float(x):
    try:
        float(x)
    except:
        return False
    return True

In [26]:
df1[~df1.max_power.apply(is_float)]

Empty DataFrame
Columns: [car_name, brand, model, vehicle_age, km_driven, seller_type, fuel_type, transmission_type, mileage, engine, max_power, seats, selling_price]
Index: []

In [27]:
df1.max_power.describe()

count    15409.000000
mean       100.587779
std         42.975721
min         38.400000
25%         74.000000
50%         88.500000
75%        117.300000
max        626.000000
Name: max_power, dtype: float64

In [28]:
df1.engine.unique()

array([ 796, 1197,  998, 1498, 1582, 1461, 1998, 1248, 2143, 2494, 1598,
       1497, 2523, 2982,  999, 1199, 1086, 2179, 1396, 1198, 1590, 1997,
       1493, 1120, 1196, 1186, 1061,  799, 1796, 2993, 1298, 3198, 1995,
       1373, 1591, 1968, 1399, 1047, 1353, 2755, 1395, 2498, 1999, 2953,
       2393, 2967, 2998, 2995, 1956, 1462, 1799, 2499, 1451, 1194, 1798,
       2694, 1496, 1969, 2487, 3604, 1499, 2987, 1599, 2354, 1950, 2148,
       4134, 2400, 1984, 2979, 2609, 2092, 5998, 1330, 2956, 3598, 2362,
        793, 1368, 3597, 1991, 5461, 1343, 2497, 4367, 1797, 3498, 2698,
       1896, 2999, 3855, 4806, 1985, 2771, 2157, 3628, 2198, 2996, 2199,
       4395, 3456, 4663, 2773, 6592, 2495, 1781, 2997, 1597, 2596, 4163])

In [29]:
df1.mileage.unique()

array([19.7 , 18.9 , 17.  , 20.92, 22.77, 20.36, 20.51, 18.15, 16.6 ,
       22.32, 19.64, 14.41, 28.09, 25.2 , 19.27, 28.4 , 12.99, 21.4 ,
       20.85, 16.09, 19.67, 17.4 , 13.6 , 26.59, 17.7 , 17.19, 13.  ,
       23.01, 18.6 , 17.92, 15.1 , 23.4 , 22.54, 18.  , 21.  , 15.4 ,
       20.89, 26.6 , 22.5 , 17.8 , 20.54, 17.3 , 25.  , 24.  , 18.16,
       21.21, 14.  , 16.8 , 25.17, 24.3 , 18.5 , 23.84, 18.78, 11.74,
       25.1 , 21.01, 22.74, 21.9 , 15.6 , 19.1 , 22.07, 22.  , 23.1 ,
       23.  , 19.08, 18.27, 23.9 , 16.1 , 19.81, 19.44, 18.59, 20.62,
       17.01, 17.5 , 12.05, 25.83, 21.79, 13.7 , 16.47, 20.7 , 10.91,
       25.8 , 25.32, 19.87, 18.7 , 14.4 , 22.69, 20.73, 16.55, 20.  ,
       21.5 , 24.7 , 23.95, 21.63, 17.43, 25.47, 33.54, 15.96, 21.19,
       26.  , 12.55, 16.9 , 22.3 , 12.9 , 13.5 , 17.84, 27.28, 24.04,
       22.7 , 16.  , 17.6 , 21.7 , 20.45, 17.14, 19.6 , 20.4 , 12.63,
       17.1 , 15.37, 11.4 , 13.68, 17.68, 12.3 , 12.19, 17.33, 20.77,
       12.07, 20.3 ,

In [30]:
df1[~df1.mileage.apply(is_float)]

Empty DataFrame
Columns: [car_name, brand, model, vehicle_age, km_driven, seller_type, fuel_type, transmission_type, mileage, engine, max_power, seats, selling_price]
Index: []

In [31]:
df1.head()

car_name    brand     model  vehicle_age  km_driven seller_type  \
0    Maruti Alto   Maruti      Alto            9     120000  Individual   
1  Hyundai Grand  Hyundai     Grand            5      20000  Individual   
2    Hyundai i20  Hyundai       i20           11      60000  Individual   
3    Maruti Alto   Maruti      Alto            9      37000  Individual   
4  Ford Ecosport     Ford  Ecosport            6      30000      Dealer   

  fuel_type transmission_type  mileage  engine  max_power  seats  \
0    Petrol            Manual    19.70     796      46.30      5   
1    Petrol            Manual    18.90    1197      82.00      5   
2    Petrol            Manual    17.00    1197      80.00      5   
3    Petrol            Manual    20.92     998      67.10      5   
4    Diesel            Manual    22.77    1498      98.59      5   

   selling_price  
0         120000  
1         550000  
2         215000  
3         226000  
4         570000

In [32]:
df1.transmission_type.unique()

array(['Manual', 'Automatic'], dtype=object)

In [33]:
df1.fuel_type.unique()

array(['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric'], dtype=object)

In [34]:
df1.seller_type.unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [35]:
df1.km_driven.unique()

array([ 120000,   20000,   60000, ...,    9229,   10723, 3800000],
      shape=(3688,))

In [36]:
df1[~df1.km_driven.apply(is_float)]

Empty DataFrame
Columns: [car_name, brand, model, vehicle_age, km_driven, seller_type, fuel_type, transmission_type, mileage, engine, max_power, seats, selling_price]
Index: []

In [37]:
df1.vehicle_age.unique()

array([ 9,  5, 11,  6,  8,  3,  2,  4,  7, 10, 14, 12,  1, 15, 13, 16, 17,
       18, 29, 19,  0, 21, 22, 25])

In [38]:
df1.model.unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       

In [39]:
df1.brand.unique()

array(['Maruti', 'Hyundai', 'Ford', 'Renault', 'Mini', 'Mercedes-Benz',
       'Toyota', 'Volkswagen', 'Honda', 'Mahindra', 'Datsun', 'Tata',
       'Kia', 'BMW', 'Audi', 'Land Rover', 'Jaguar', 'MG', 'Isuzu',
       'Porsche', 'Skoda', 'Volvo', 'Lexus', 'Jeep', 'Maserati',
       'Bentley', 'Nissan', 'ISUZU', 'Ferrari', 'Mercedes-AMG',
       'Rolls-Royce', 'Force'], dtype=object)

In [40]:
df1.head()

car_name    brand     model  vehicle_age  km_driven seller_type  \
0    Maruti Alto   Maruti      Alto            9     120000  Individual   
1  Hyundai Grand  Hyundai     Grand            5      20000  Individual   
2    Hyundai i20  Hyundai       i20           11      60000  Individual   
3    Maruti Alto   Maruti      Alto            9      37000  Individual   
4  Ford Ecosport     Ford  Ecosport            6      30000      Dealer   

  fuel_type transmission_type  mileage  engine  max_power  seats  \
0    Petrol            Manual    19.70     796      46.30      5   
1    Petrol            Manual    18.90    1197      82.00      5   
2    Petrol            Manual    17.00    1197      80.00      5   
3    Petrol            Manual    20.92     998      67.10      5   
4    Diesel            Manual    22.77    1498      98.59      5   

   selling_price  
0         120000  
1         550000  
2         215000  
3         226000  
4         570000

In [41]:
df2 = df1.drop('car_name', axis="columns")

In [42]:
df2.head()

brand     model  vehicle_age  km_driven seller_type fuel_type  \
0   Maruti      Alto            9     120000  Individual    Petrol   
1  Hyundai     Grand            5      20000  Individual    Petrol   
2  Hyundai       i20           11      60000  Individual    Petrol   
3   Maruti      Alto            9      37000  Individual    Petrol   
4     Ford  Ecosport            6      30000      Dealer    Diesel   

  transmission_type  mileage  engine  max_power  seats  selling_price  
0            Manual    19.70     796      46.30      5         120000  
1            Manual    18.90    1197      82.00      5         550000  
2            Manual    17.00    1197      80.00      5         215000  
3            Manual    20.92     998      67.10      5         226000  
4            Manual    22.77    1498      98.59      5         570000

In [44]:
brand_dummy = pd.get_dummies(df2.brand)
model_dummy = pd.get_dummies(df2. model)
seller_type_dummy = pd.get_dummies(df2.seller_type)
fuel_type_dummy = pd.get_dummies(df2.fuel_type)
transmission_type_dummy = pd.get_dummies(df2.transmission_type)

In [46]:
df3 = df2.copy()

In [47]:
df3.head()

brand     model  vehicle_age  km_driven seller_type fuel_type  \
0   Maruti      Alto            9     120000  Individual    Petrol   
1  Hyundai     Grand            5      20000  Individual    Petrol   
2  Hyundai       i20           11      60000  Individual    Petrol   
3   Maruti      Alto            9      37000  Individual    Petrol   
4     Ford  Ecosport            6      30000      Dealer    Diesel   

  transmission_type  mileage  engine  max_power  seats  selling_price  
0            Manual    19.70     796      46.30      5         120000  
1            Manual    18.90    1197      82.00      5         550000  
2            Manual    17.00    1197      80.00      5         215000  
3            Manual    20.92     998      67.10      5         226000  
4            Manual    22.77    1498      98.59      5         570000

In [48]:
df3 = pd.concat([df3, brand_dummy, model_dummy, seller_type_dummy, fuel_type_dummy, transmission_type_dummy], axis="columns")

In [49]:
df3.head()

brand     model  vehicle_age  km_driven seller_type fuel_type  \
0   Maruti      Alto            9     120000  Individual    Petrol   
1  Hyundai     Grand            5      20000  Individual    Petrol   
2  Hyundai       i20           11      60000  Individual    Petrol   
3   Maruti      Alto            9      37000  Individual    Petrol   
4     Ford  Ecosport            6      30000      Dealer    Diesel   

  transmission_type  mileage  engine  max_power  ...  Dealer  Individual  \
0            Manual    19.70     796      46.30  ...   False        True   
1            Manual    18.90    1197      82.00  ...   False        True   
2            Manual    17.00    1197      80.00  ...   False        True   
3            Manual    20.92     998      67.10  ...   False        True   
4            Manual    22.77    1498      98.59  ...    True       False   

   Trustmark Dealer    CNG  Diesel  Electric    LPG  Petrol  Automatic  Manual  
0             False  False   False     False  False    True      False    True  
1             False  False   False     False  False    True      False    True  
2             False  False   False     False  False    True      False    True  
3             False  False   False     False  False    True      False    True  
4             False  False    True     False  False   False      False    True  

[5 rows x 174 columns]

In [50]:
df4 = df3.drop(['brand', 'model', 'seller_type', 'fuel_type', 'transmission_type'], axis="columns")

In [51]:
df4.head()

vehicle_age  km_driven  mileage  engine  max_power  seats  selling_price  \
0            9     120000    19.70     796      46.30      5         120000   
1            5      20000    18.90    1197      82.00      5         550000   
2           11      60000    17.00    1197      80.00      5         215000   
3            9      37000    20.92     998      67.10      5         226000   
4            6      30000    22.77    1498      98.59      5         570000   

    Audi    BMW  Bentley  ...  Dealer  Individual  Trustmark Dealer    CNG  \
0  False  False    False  ...   False        True             False  False   
1  False  False    False  ...   False        True             False  False   
2  False  False    False  ...   False        True             False  False   
3  False  False    False  ...   False        True             False  False   
4  False  False    False  ...    True       False             False  False   

   Diesel  Electric    LPG  Petrol  Automatic  Manual  
0   False     False  False    True      False    True  
1   False     False  False    True      False    True  
2   False     False  False    True      False    True  
3   False     False  False    True      False    True  
4    True     False  False   False      False    True  

[5 rows x 169 columns]

In [52]:
X = df4.drop('selling_price', axis="columns")
y = df4['selling_price']

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [55]:
from sklearn.linear_model import LinearRegression

In [56]:
lr_model = LinearRegression()

In [57]:
lr_model.fit(X_train, y_train) 

LinearRegression()

In [58]:
lr_model.score(X_test, y_test)

0.7911709629377228

In [67]:
from sklearn.tree import DecisionTreeRegressor

In [68]:
tree_model = DecisionTreeRegressor()

In [69]:
tree_model.fit(X_train, y_train)

DecisionTreeRegressor()

In [70]:
tree_model.score(X_test, y_test)

0.8864165519342926

In [82]:
from sklearn.ensemble import RandomForestRegressor

In [83]:
rfc_model = RandomForestRegressor()

In [84]:
rfc_model.fit(X_train, y_train)

RandomForestRegressor()

In [85]:
rfc_model.score(X_test, y_test)

0.9368698375807328

In [86]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

In [87]:
cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
cvs = cross_val_score(DecisionTreeRegressor(), X, y, cv=cv)

In [88]:
cvs

array([0.24234745, 0.69710734, 0.68315196, 0.88743978, 0.91888049])

In [89]:
cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
cvs = cross_val_score(RandomForestRegressor(), X, y, cv=cv)

In [91]:
cvs

array([0.88511834, 0.76795566, 0.93944247, 0.92672877, 0.94618778])

In [75]:
from sklearn.linear_model import Lasso

In [76]:
from sklearn.model_selection import GridSearchCV

In [92]:
def find_best_model(X,y):
    algos = {
        'linear_regression' : {
            'model' : LinearRegression(),
            'params' : {}
        },
        'lasso' : {
            'model' : Lasso(),
            'params' : {
                'alpha' : [1,2],
                'selection' : ['random', 'cyclic']
            }
        },
        'decision_tree' : {
            'model' : DecisionTreeRegressor(),
            'params' : {
                'criterion' : ['mse', 'friedman_mse'],
                'splitter' : ['best', 'random']
            }
        },
        'random_forest' : {
            'model' : RandomForestRegressor(),
            'params' : {
                'n_estimators' : [1,5,10]
            }
        }
        
    }

    scores = []
    cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
    for algo_name, config in algos.items():
        gcv = GridSearchCV(config['model'], config['params'], cv=cv, return_train_score=False)
        gcv.fit(X, y)
        scores.append({
            'model' : algo_name,
            'best_score' : gcv.best_score_,
            'best_param' : gcv.best_params_
        })
    return pd.DataFrame(scores, columns=['model', 'best_score', 'best_param'])

In [93]:
find_best_model(X, y)

C:\Users\Smart Computers\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.108e+14, tolerance: 9.457e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\Smart Computers\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.660e+14, tolerance: 8.367e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\Smart Computers\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale 

model  best_score  \
0  linear_regression    0.721130   
1              lasso    0.709083   
2      decision_tree    0.808006   
3      random_forest    0.875608   

                                          best_param  
0                                                 {}  
1                {'alpha': 2, 'selection': 'cyclic'}  
2  {'criterion': 'friedman_mse', 'splitter': 'ran...  
3                               {'n_estimators': 10}

In [79]:
cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
cvs = cross_val_score(DecisionTreeRegressor(), X, y, cv=cv)

In [80]:
cvs.mean()

np.float64(0.8135568044597937)

In [97]:
X.head()

vehicle_age  km_driven  mileage  engine  max_power  seats   Audi    BMW  \
0            9     120000    19.70     796      46.30      5  False  False   
1            5      20000    18.90    1197      82.00      5  False  False   
2           11      60000    17.00    1197      80.00      5  False  False   
3            9      37000    20.92     998      67.10      5  False  False   
4            6      30000    22.77    1498      98.59      5  False  False   

   Bentley  Datsun  ...  Dealer  Individual  Trustmark Dealer    CNG  Diesel  \
0    False   False  ...   False        True             False  False   False   
1    False   False  ...   False        True             False  False   False   
2    False   False  ...   False        True             False  False   False   
3    False   False  ...   False        True             False  False   False   
4    False   False  ...    True       False             False  False    True   

   Electric    LPG  Petrol  Automatic  Manual  
0     False  False    True      False    True  
1     False  False    True      False    True  
2     False  False    True      False    True  
3     False  False    True      False    True  
4     False  False   False      False    True  

[5 rows x 168 columns]

In [95]:
def predict_price(vehicle_age, km_driven, mileage, engine, max_power, seats, brand, model, seller_type, fuel_type, transmission_type):
    brand_loc = np.where(X.columns == brand)[0][0]
    model_loc = np.where(X.columns == model)[0][0]
    seller_type_loc = np.where(X.columns == seller_type)[0][0]
    fuel_type_loc = np.where(X.columns == fuel_type)[0][0]
    transmission_type_loc = np.where(X.columns == transmission_type)[0][0]

    x = np.zeros(len(X.columns))
    x[0] = vehicle_age
    x[1] = km_driven
    x[2] = mileage
    x[3] = engine
    x[4] = max_power
    x[5] = seats
    
    if brand_loc>=0:
        x[brand_loc] = 1
    if model_loc>=0:
        x[model_loc] = 1
    if seller_type_loc>=0:
        x[seller_type_loc] = 1
    if fuel_type_loc>=0:
        x[fuel_type_loc] = 1
    if transmission_type_loc>=0:
        x[transmission_type_loc] = 1

    return rfc_model.predict([x])[0]

In [113]:
predict_price(1, 2000, 19.9, 1197, 200, 2, 'Hyundai', 'Grand', 'Individual', 'Petrol', 'Manual')

C:\Users\Smart Computers\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


np.float64(3603500.0)